// Code generated by forge. DO NOT EDIT.
package markets

import (
	"time"

	"github.com/forgego/forge/orm"
	validation "github.com/forgego/forge/validate"
)

// Validate validates the Asset model
func (m *Asset) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// AssetObjects provides type-safe operations for Asset
// Uses generic orm.Manager[Asset] and orm.BaseQuerySet[Asset]
var AssetObjects, _ = orm.NewManager[Asset]("assets")

func init() {
	if AssetObjects != nil {
		orm.RegisterManagerFor[Asset](AssetObjects)
	}
}

// AssetFields provides type-safe field access for Asset
type AssetFields struct {
	Id        orm.FieldExpression[int64]
	Symbol    orm.FieldExpression[string]
	Name      orm.FieldExpression[string]
	AssetType orm.FieldExpression[string]
	Precision orm.FieldExpression[int32]
	IsActive  orm.FieldExpression[bool]
	CreatedAt orm.FieldExpression[time.Time]
	UpdatedAt orm.FieldExpression[time.Time]
}

var AssetFieldsInstance = AssetFields{
	Id:        orm.NewField[int64]("id", "assets"),
	Symbol:    orm.NewField[string]("symbol", "assets"),
	Name:      orm.NewField[string]("name", "assets"),
	AssetType: orm.NewField[string]("asset_type", "assets"),
	Precision: orm.NewField[int32]("precision", "assets"),
	IsActive:  orm.NewField[bool]("is_active", "assets"),
	CreatedAt: orm.NewField[time.Time]("created_at", "assets"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "assets"),
}

// Validate validates the TradingPair model
func (m *TradingPair) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// TradingPairObjects provides type-safe operations for TradingPair
// Uses generic orm.Manager[TradingPair] and orm.BaseQuerySet[TradingPair]
var TradingPairObjects, _ = orm.NewManager[TradingPair]("trading_pairs")

func init() {
	if TradingPairObjects != nil {
		orm.RegisterManagerFor[TradingPair](TradingPairObjects)
	}
}

// TradingPairFields provides type-safe field access for TradingPair
type TradingPairFields struct {
	Id           orm.FieldExpression[int64]
	Symbol       orm.FieldExpression[string]
	BaseAssetId  orm.FieldExpression[int64]
	QuoteAssetId orm.FieldExpression[int64]
	Status       orm.FieldExpression[string]
	MinPrice     orm.FieldExpression[float64]
	MaxPrice     orm.FieldExpression[float64]
	PriceTick    orm.FieldExpression[float64]
	QtyStep      orm.FieldExpression[float64]
	CreatedAt    orm.FieldExpression[time.Time]
	UpdatedAt    orm.FieldExpression[time.Time]
}

var TradingPairFieldsInstance = TradingPairFields{
	Id:           orm.NewField[int64]("id", "trading_pairs"),
	Symbol:       orm.NewField[string]("symbol", "trading_pairs"),
	BaseAssetId:  orm.NewField[int64]("base_asset_id", "trading_pairs"),
	QuoteAssetId: orm.NewField[int64]("quote_asset_id", "trading_pairs"),
	Status:       orm.NewField[string]("status", "trading_pairs"),
	MinPrice:     orm.NewField[float64]("min_price", "trading_pairs"),
	MaxPrice:     orm.NewField[float64]("max_price", "trading_pairs"),
	PriceTick:    orm.NewField[float64]("price_tick", "trading_pairs"),
	QtyStep:      orm.NewField[float64]("qty_step", "trading_pairs"),
	CreatedAt:    orm.NewField[time.Time]("created_at", "trading_pairs"),
	UpdatedAt:    orm.NewField[time.Time]("updated_at", "trading_pairs"),
}
