// Code generated by forge. DO NOT EDIT.
package accounts

import (
	"time"

	"github.com/forgego/forge/orm"
	validation "github.com/forgego/forge/validate"
)

// Validate validates the UserProfile model
func (m *UserProfile) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// UserProfileObjects provides type-safe operations for UserProfile
// Uses generic orm.Manager[UserProfile] and orm.BaseQuerySet[UserProfile]
var UserProfileObjects, _ = orm.NewManager[UserProfile]("user_profiles")

func init() {
	if UserProfileObjects != nil {
		orm.RegisterManagerFor[UserProfile](UserProfileObjects)
	}
}

// UserProfileFields provides type-safe field access for UserProfile
type UserProfileFields struct {
	Id          orm.FieldExpression[int64]
	UserId      orm.FieldExpression[int64]
	DisplayName orm.FieldExpression[string]
	Email       orm.FieldExpression[string]
	Tier        orm.FieldExpression[string]
	IsActive    orm.FieldExpression[bool]
	CreatedAt   orm.FieldExpression[time.Time]
	UpdatedAt   orm.FieldExpression[time.Time]
}

var UserProfileFieldsInstance = UserProfileFields{
	Id:          orm.NewField[int64]("id", "user_profiles"),
	UserId:      orm.NewField[int64]("user_id", "user_profiles"),
	DisplayName: orm.NewField[string]("display_name", "user_profiles"),
	Email:       orm.NewField[string]("email", "user_profiles"),
	Tier:        orm.NewField[string]("tier", "user_profiles"),
	IsActive:    orm.NewField[bool]("is_active", "user_profiles"),
	CreatedAt:   orm.NewField[time.Time]("created_at", "user_profiles"),
	UpdatedAt:   orm.NewField[time.Time]("updated_at", "user_profiles"),
}

// Validate validates the APIKey model
func (m *APIKey) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// APIKeyObjects provides type-safe operations for APIKey
// Uses generic orm.Manager[APIKey] and orm.BaseQuerySet[APIKey]
var APIKeyObjects, _ = orm.NewManager[APIKey]("api_keys")

func init() {
	if APIKeyObjects != nil {
		orm.RegisterManagerFor[APIKey](APIKeyObjects)
	}
}

// APIKeyFields provides type-safe field access for APIKey
type APIKeyFields struct {
	Id        orm.FieldExpression[int64]
	UserId    orm.FieldExpression[int64]
	Name      orm.FieldExpression[string]
	Key       orm.FieldExpression[string]
	Secret    orm.FieldExpression[string]
	IsActive  orm.FieldExpression[bool]
	CreatedAt orm.FieldExpression[time.Time]
	UpdatedAt orm.FieldExpression[time.Time]
}

var APIKeyFieldsInstance = APIKeyFields{
	Id:        orm.NewField[int64]("id", "api_keys"),
	UserId:    orm.NewField[int64]("user_id", "api_keys"),
	Name:      orm.NewField[string]("name", "api_keys"),
	Key:       orm.NewField[string]("key", "api_keys"),
	Secret:    orm.NewField[string]("secret", "api_keys"),
	IsActive:  orm.NewField[bool]("is_active", "api_keys"),
	CreatedAt: orm.NewField[time.Time]("created_at", "api_keys"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "api_keys"),
}
