// Code generated by forge. DO NOT EDIT.
package commerce

import (
	"time"
	"github.com/forgego/forge/orm"
	"github.com/forgego/forge/schema"
	validate "github.com/forgego/forge/validate"
)


// ShippingMethodGenerated struct definition
type ShippingMethodGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	Name string `json:"name" db:"name" validate:"required,max=200"`
	Code string `json:"code" db:"code" validate:"required,max=50"`
	Description string `json:"description" db:"description" validate:""`
	BasePrice float64 `json:"base_price" db:"base_price" validate:""`
	PricePerKg float64 `json:"price_per_kg" db:"price_per_kg" validate:""`
	EstimatedDaysMin int32 `json:"estimated_days_min" db:"estimated_days_min" validate:""`
	EstimatedDaysMax int32 `json:"estimated_days_max" db:"estimated_days_max" validate:""`
	IsActive bool `json:"is_active" db:"is_active" validate:""`
	SortOrder int32 `json:"sort_order" db:"sort_order" validate:""`
	CarrierName string `json:"carrier_name" db:"carrier_name" validate:"max=200"`
	TrackingUrlFormat string `json:"tracking_url_format" db:"tracking_url_format" validate:"max=500"`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the ShippingMethod model
func (m *ShippingMethod) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// ShippingMethodObjects provides type-safe operations for ShippingMethod
// Uses generic orm.Manager[ShippingMethod] and orm.BaseQuerySet[ShippingMethod]
var ShippingMethodObjects, _ = orm.NewManager[ShippingMethod]("shipping_methods")

// ShippingMethodFields provides type-safe field access for ShippingMethod
type ShippingMethodFields struct {
	Id orm.Field[int64]
	Name orm.Field[string]
	Code orm.Field[string]
	Description orm.Field[string]
	BasePrice orm.Field[float64]
	PricePerKg orm.Field[float64]
	EstimatedDaysMin orm.Field[int32]
	EstimatedDaysMax orm.Field[int32]
	IsActive orm.Field[bool]
	SortOrder orm.Field[int32]
	CarrierName orm.Field[string]
	TrackingUrlFormat orm.Field[string]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var ShippingMethodFieldsInstance = ShippingMethodFields{
	Id: orm.NewField[int64]("id", "shipping_methods"),
	Name: orm.NewField[string]("name", "shipping_methods"),
	Code: orm.NewField[string]("code", "shipping_methods"),
	Description: orm.NewField[string]("description", "shipping_methods"),
	BasePrice: orm.NewField[float64]("base_price", "shipping_methods"),
	PricePerKg: orm.NewField[float64]("price_per_kg", "shipping_methods"),
	EstimatedDaysMin: orm.NewField[int32]("estimated_days_min", "shipping_methods"),
	EstimatedDaysMax: orm.NewField[int32]("estimated_days_max", "shipping_methods"),
	IsActive: orm.NewField[bool]("is_active", "shipping_methods"),
	SortOrder: orm.NewField[int32]("sort_order", "shipping_methods"),
	CarrierName: orm.NewField[string]("carrier_name", "shipping_methods"),
	TrackingUrlFormat: orm.NewField[string]("tracking_url_format", "shipping_methods"),
	CreatedAt: orm.NewField[time.Time]("created_at", "shipping_methods"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "shipping_methods"),
}




// PaymentMethodGenerated struct definition
type PaymentMethodGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	Name string `json:"name" db:"name" validate:"required,max=200"`
	Code string `json:"code" db:"code" validate:"required,max=50"`
	Description string `json:"description" db:"description" validate:""`
	ProcessorName string `json:"processor_name" db:"processor_name" validate:"max=100"`
	IsActive bool `json:"is_active" db:"is_active" validate:""`
	SortOrder int32 `json:"sort_order" db:"sort_order" validate:""`
	RequiresAuth bool `json:"requires_auth" db:"requires_auth" validate:""`
	SupportsRefund bool `json:"supports_refund" db:"supports_refund" validate:""`
	IconUrl string `json:"icon_url" db:"icon_url" validate:"max=500"`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the PaymentMethod model
func (m *PaymentMethod) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// PaymentMethodObjects provides type-safe operations for PaymentMethod
// Uses generic orm.Manager[PaymentMethod] and orm.BaseQuerySet[PaymentMethod]
var PaymentMethodObjects, _ = orm.NewManager[PaymentMethod]("payment_methods")

// PaymentMethodFields provides type-safe field access for PaymentMethod
type PaymentMethodFields struct {
	Id orm.Field[int64]
	Name orm.Field[string]
	Code orm.Field[string]
	Description orm.Field[string]
	ProcessorName orm.Field[string]
	IsActive orm.Field[bool]
	SortOrder orm.Field[int32]
	RequiresAuth orm.Field[bool]
	SupportsRefund orm.Field[bool]
	IconUrl orm.Field[string]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var PaymentMethodFieldsInstance = PaymentMethodFields{
	Id: orm.NewField[int64]("id", "payment_methods"),
	Name: orm.NewField[string]("name", "payment_methods"),
	Code: orm.NewField[string]("code", "payment_methods"),
	Description: orm.NewField[string]("description", "payment_methods"),
	ProcessorName: orm.NewField[string]("processor_name", "payment_methods"),
	IsActive: orm.NewField[bool]("is_active", "payment_methods"),
	SortOrder: orm.NewField[int32]("sort_order", "payment_methods"),
	RequiresAuth: orm.NewField[bool]("requires_auth", "payment_methods"),
	SupportsRefund: orm.NewField[bool]("supports_refund", "payment_methods"),
	IconUrl: orm.NewField[string]("icon_url", "payment_methods"),
	CreatedAt: orm.NewField[time.Time]("created_at", "payment_methods"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "payment_methods"),
}




// TaxRateGenerated struct definition
type TaxRateGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	Name string `json:"name" db:"name" validate:"required,max=200"`
	Code string `json:"code" db:"code" validate:"required,max=50"`
	Rate float64 `json:"rate" db:"rate" validate:"required"`
	Country string `json:"country" db:"country" validate:"max=2"`
	State string `json:"state" db:"state" validate:"max=100"`
	City string `json:"city" db:"city" validate:"max=100"`
	ZipCode string `json:"zip_code" db:"zip_code" validate:"max=20"`
	IsCompound bool `json:"is_compound" db:"is_compound" validate:""`
	IsActive bool `json:"is_active" db:"is_active" validate:""`
	Priority int32 `json:"priority" db:"priority" validate:""`
	ApplyToShipping bool `json:"apply_to_shipping" db:"apply_to_shipping" validate:""`
	IncludedInPrice bool `json:"included_in_price" db:"included_in_price" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the TaxRate model
func (m *TaxRate) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// TaxRateObjects provides type-safe operations for TaxRate
// Uses generic orm.Manager[TaxRate] and orm.BaseQuerySet[TaxRate]
var TaxRateObjects, _ = orm.NewManager[TaxRate]("tax_rates")

// TaxRateFields provides type-safe field access for TaxRate
type TaxRateFields struct {
	Id orm.Field[int64]
	Name orm.Field[string]
	Code orm.Field[string]
	Rate orm.Field[float64]
	Country orm.Field[string]
	State orm.Field[string]
	City orm.Field[string]
	ZipCode orm.Field[string]
	IsCompound orm.Field[bool]
	IsActive orm.Field[bool]
	Priority orm.Field[int32]
	ApplyToShipping orm.Field[bool]
	IncludedInPrice orm.Field[bool]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var TaxRateFieldsInstance = TaxRateFields{
	Id: orm.NewField[int64]("id", "tax_rates"),
	Name: orm.NewField[string]("name", "tax_rates"),
	Code: orm.NewField[string]("code", "tax_rates"),
	Rate: orm.NewField[float64]("rate", "tax_rates"),
	Country: orm.NewField[string]("country", "tax_rates"),
	State: orm.NewField[string]("state", "tax_rates"),
	City: orm.NewField[string]("city", "tax_rates"),
	ZipCode: orm.NewField[string]("zip_code", "tax_rates"),
	IsCompound: orm.NewField[bool]("is_compound", "tax_rates"),
	IsActive: orm.NewField[bool]("is_active", "tax_rates"),
	Priority: orm.NewField[int32]("priority", "tax_rates"),
	ApplyToShipping: orm.NewField[bool]("apply_to_shipping", "tax_rates"),
	IncludedInPrice: orm.NewField[bool]("included_in_price", "tax_rates"),
	CreatedAt: orm.NewField[time.Time]("created_at", "tax_rates"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "tax_rates"),
}




// CurrencyGenerated struct definition
type CurrencyGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	Code string `json:"code" db:"code" validate:"required,max=3"`
	Name string `json:"name" db:"name" validate:"required,max=100"`
	Symbol string `json:"symbol" db:"symbol" validate:"max=10"`
	DecimalPlaces int32 `json:"decimal_places" db:"decimal_places" validate:""`
	IsActive bool `json:"is_active" db:"is_active" validate:""`
	IsDefault bool `json:"is_default" db:"is_default" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the Currency model
func (m *Currency) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// CurrencyObjects provides type-safe operations for Currency
// Uses generic orm.Manager[Currency] and orm.BaseQuerySet[Currency]
var CurrencyObjects, _ = orm.NewManager[Currency]("currencies")

// CurrencyFields provides type-safe field access for Currency
type CurrencyFields struct {
	Id orm.Field[int64]
	Code orm.Field[string]
	Name orm.Field[string]
	Symbol orm.Field[string]
	DecimalPlaces orm.Field[int32]
	IsActive orm.Field[bool]
	IsDefault orm.Field[bool]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var CurrencyFieldsInstance = CurrencyFields{
	Id: orm.NewField[int64]("id", "currencies"),
	Code: orm.NewField[string]("code", "currencies"),
	Name: orm.NewField[string]("name", "currencies"),
	Symbol: orm.NewField[string]("symbol", "currencies"),
	DecimalPlaces: orm.NewField[int32]("decimal_places", "currencies"),
	IsActive: orm.NewField[bool]("is_active", "currencies"),
	IsDefault: orm.NewField[bool]("is_default", "currencies"),
	CreatedAt: orm.NewField[time.Time]("created_at", "currencies"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "currencies"),
}




// ExchangeRateGenerated struct definition
type ExchangeRateGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	FromCurrencyId int64 `json:"from_currency_id" db:"from_currency_id" validate:"required"`
	ToCurrencyId int64 `json:"to_currency_id" db:"to_currency_id" validate:"required"`
	Rate float64 `json:"rate" db:"rate" validate:"required"`
	EffectiveDate time.Time `json:"effective_date" db:"effective_date" validate:"required"`
	Source string `json:"source" db:"source" validate:"max=100"`
	IsActive bool `json:"is_active" db:"is_active" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the ExchangeRate model
func (m *ExchangeRate) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// ExchangeRateObjects provides type-safe operations for ExchangeRate
// Uses generic orm.Manager[ExchangeRate] and orm.BaseQuerySet[ExchangeRate]
var ExchangeRateObjects, _ = orm.NewManager[ExchangeRate]("exchange_rates")

// ExchangeRateFields provides type-safe field access for ExchangeRate
type ExchangeRateFields struct {
	Id orm.Field[int64]
	FromCurrencyId orm.Field[int64]
	ToCurrencyId orm.Field[int64]
	Rate orm.Field[float64]
	EffectiveDate orm.Field[time.Time]
	Source orm.Field[string]
	IsActive orm.Field[bool]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var ExchangeRateFieldsInstance = ExchangeRateFields{
	Id: orm.NewField[int64]("id", "exchange_rates"),
	FromCurrencyId: orm.NewField[int64]("from_currency_id", "exchange_rates"),
	ToCurrencyId: orm.NewField[int64]("to_currency_id", "exchange_rates"),
	Rate: orm.NewField[float64]("rate", "exchange_rates"),
	EffectiveDate: orm.NewField[time.Time]("effective_date", "exchange_rates"),
	Source: orm.NewField[string]("source", "exchange_rates"),
	IsActive: orm.NewField[bool]("is_active", "exchange_rates"),
	CreatedAt: orm.NewField[time.Time]("created_at", "exchange_rates"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "exchange_rates"),
}




