// Code generated by forge. DO NOT EDIT.
package ledger

import (
	"time"

	"github.com/forgego/forge/orm"
	validation "github.com/forgego/forge/validate"
)

// Validate validates the LedgerEntry model
func (m *LedgerEntry) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// LedgerEntryObjects provides type-safe operations for LedgerEntry
// Uses generic orm.Manager[LedgerEntry] and orm.BaseQuerySet[LedgerEntry]
var LedgerEntryObjects, _ = orm.NewManager[LedgerEntry]("ledger_entries")

func init() {
	if LedgerEntryObjects != nil {
		orm.RegisterManagerFor[LedgerEntry](LedgerEntryObjects)
	}
}

// LedgerEntryFields provides type-safe field access for LedgerEntry
type LedgerEntryFields struct {
	Id           orm.FieldExpression[int64]
	UserId       orm.FieldExpression[int64]
	AssetId      orm.FieldExpression[int64]
	EntryType    orm.FieldExpression[string]
	Amount       orm.FieldExpression[float64]
	BalanceAfter orm.FieldExpression[float64]
	RefType      orm.FieldExpression[string]
	RefId        orm.FieldExpression[int64]
	CreatedAt    orm.FieldExpression[time.Time]
}

var LedgerEntryFieldsInstance = LedgerEntryFields{
	Id:           orm.NewField[int64]("id", "ledger_entries"),
	UserId:       orm.NewField[int64]("user_id", "ledger_entries"),
	AssetId:      orm.NewField[int64]("asset_id", "ledger_entries"),
	EntryType:    orm.NewField[string]("entry_type", "ledger_entries"),
	Amount:       orm.NewField[float64]("amount", "ledger_entries"),
	BalanceAfter: orm.NewField[float64]("balance_after", "ledger_entries"),
	RefType:      orm.NewField[string]("ref_type", "ledger_entries"),
	RefId:        orm.NewField[int64]("ref_id", "ledger_entries"),
	CreatedAt:    orm.NewField[time.Time]("created_at", "ledger_entries"),
}
