// Code generated by forge. DO NOT EDIT.
package marketing

import (
	"time"
	"github.com/forgego/forge/orm"
	"github.com/forgego/forge/schema"
	validate "github.com/forgego/forge/validate"
)


// CouponGenerated struct definition
type CouponGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	Code string `json:"code" db:"code" validate:""`
	Name string `json:"name" db:"name" validate:""`
	Description string `json:"description" db:"description" validate:""`
	DiscountType string `json:"discount_type" db:"discount_type" validate:""`
	DiscountValue float64 `json:"discount_value" db:"discount_value" validate:""`
	MinimumPurchaseAmount float64 `json:"minimum_purchase_amount" db:"minimum_purchase_amount" validate:""`
	MaximumDiscountAmount float64 `json:"maximum_discount_amount" db:"maximum_discount_amount" validate:""`
	UsageLimit int32 `json:"usage_limit" db:"usage_limit" validate:""`
	UsageLimitPerCustomer int32 `json:"usage_limit_per_customer" db:"usage_limit_per_customer" validate:""`
	UsageCount int32 `json:"usage_count" db:"usage_count" validate:""`
	AppliesToAllProducts bool `json:"applies_to_all_products" db:"applies_to_all_products" validate:""`
	ProductIds string `json:"product_ids" db:"product_ids" validate:""`
	CategoryIds string `json:"category_ids" db:"category_ids" validate:""`
	ExcludedProductIds string `json:"excluded_product_ids" db:"excluded_product_ids" validate:""`
	AppliesToAllCustomers bool `json:"applies_to_all_customers" db:"applies_to_all_customers" validate:""`
	CustomerGroupIds string `json:"customer_group_ids" db:"customer_group_ids" validate:""`
	CustomerEmailList string `json:"customer_email_list" db:"customer_email_list" validate:""`
	ValidFrom time.Time `json:"valid_from" db:"valid_from" validate:""`
	ValidUntil time.Time `json:"valid_until" db:"valid_until" validate:""`
	IsActive bool `json:"is_active" db:"is_active" validate:""`
	IsPublic bool `json:"is_public" db:"is_public" validate:""`
	Priority int32 `json:"priority" db:"priority" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the Coupon model
func (m *Coupon) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// CouponObjects provides type-safe operations for Coupon
// Uses generic orm.Manager[Coupon] and orm.BaseQuerySet[Coupon]
var CouponObjects, _ = orm.NewManager[Coupon]("coupons")

// CouponFields provides type-safe field access for Coupon
type CouponFields struct {
	Id orm.Field[int64]
	Code orm.Field[string]
	Name orm.Field[string]
	Description orm.Field[string]
	DiscountType orm.Field[string]
	DiscountValue orm.Field[float64]
	MinimumPurchaseAmount orm.Field[float64]
	MaximumDiscountAmount orm.Field[float64]
	UsageLimit orm.Field[int32]
	UsageLimitPerCustomer orm.Field[int32]
	UsageCount orm.Field[int32]
	AppliesToAllProducts orm.Field[bool]
	ProductIds orm.Field[string]
	CategoryIds orm.Field[string]
	ExcludedProductIds orm.Field[string]
	AppliesToAllCustomers orm.Field[bool]
	CustomerGroupIds orm.Field[string]
	CustomerEmailList orm.Field[string]
	ValidFrom orm.Field[time.Time]
	ValidUntil orm.Field[time.Time]
	IsActive orm.Field[bool]
	IsPublic orm.Field[bool]
	Priority orm.Field[int32]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var CouponFieldsInstance = CouponFields{
	Id: orm.NewField[int64]("id", "coupons"),
	Code: orm.NewField[string]("code", "coupons"),
	Name: orm.NewField[string]("name", "coupons"),
	Description: orm.NewField[string]("description", "coupons"),
	DiscountType: orm.NewField[string]("discount_type", "coupons"),
	DiscountValue: orm.NewField[float64]("discount_value", "coupons"),
	MinimumPurchaseAmount: orm.NewField[float64]("minimum_purchase_amount", "coupons"),
	MaximumDiscountAmount: orm.NewField[float64]("maximum_discount_amount", "coupons"),
	UsageLimit: orm.NewField[int32]("usage_limit", "coupons"),
	UsageLimitPerCustomer: orm.NewField[int32]("usage_limit_per_customer", "coupons"),
	UsageCount: orm.NewField[int32]("usage_count", "coupons"),
	AppliesToAllProducts: orm.NewField[bool]("applies_to_all_products", "coupons"),
	ProductIds: orm.NewField[string]("product_ids", "coupons"),
	CategoryIds: orm.NewField[string]("category_ids", "coupons"),
	ExcludedProductIds: orm.NewField[string]("excluded_product_ids", "coupons"),
	AppliesToAllCustomers: orm.NewField[bool]("applies_to_all_customers", "coupons"),
	CustomerGroupIds: orm.NewField[string]("customer_group_ids", "coupons"),
	CustomerEmailList: orm.NewField[string]("customer_email_list", "coupons"),
	ValidFrom: orm.NewField[time.Time]("valid_from", "coupons"),
	ValidUntil: orm.NewField[time.Time]("valid_until", "coupons"),
	IsActive: orm.NewField[bool]("is_active", "coupons"),
	IsPublic: orm.NewField[bool]("is_public", "coupons"),
	Priority: orm.NewField[int32]("priority", "coupons"),
	CreatedAt: orm.NewField[time.Time]("created_at", "coupons"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "coupons"),
}




// CouponUsageGenerated struct definition
type CouponUsageGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	CouponId int64 `json:"coupon_id" db:"coupon_id" validate:""`
	OrderId int64 `json:"order_id" db:"order_id" validate:""`
	CustomerId int64 `json:"customer_id" db:"customer_id" validate:""`
	DiscountAmount float64 `json:"discount_amount" db:"discount_amount" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
}

// Validate validates the CouponUsage model
func (m *CouponUsage) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// CouponUsageObjects provides type-safe operations for CouponUsage
// Uses generic orm.Manager[CouponUsage] and orm.BaseQuerySet[CouponUsage]
var CouponUsageObjects, _ = orm.NewManager[CouponUsage]("coupon_usage")

// CouponUsageFields provides type-safe field access for CouponUsage
type CouponUsageFields struct {
	Id orm.Field[int64]
	CouponId orm.Field[int64]
	OrderId orm.Field[int64]
	CustomerId orm.Field[int64]
	DiscountAmount orm.Field[float64]
	CreatedAt orm.Field[time.Time]
}

var CouponUsageFieldsInstance = CouponUsageFields{
	Id: orm.NewField[int64]("id", "coupon_usage"),
	CouponId: orm.NewField[int64]("coupon_id", "coupon_usage"),
	OrderId: orm.NewField[int64]("order_id", "coupon_usage"),
	CustomerId: orm.NewField[int64]("customer_id", "coupon_usage"),
	DiscountAmount: orm.NewField[float64]("discount_amount", "coupon_usage"),
	CreatedAt: orm.NewField[time.Time]("created_at", "coupon_usage"),
}




// ReviewGenerated struct definition
type ReviewGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	ProductId int64 `json:"product_id" db:"product_id" validate:""`
	CustomerId int64 `json:"customer_id" db:"customer_id" validate:""`
	OrderId int64 `json:"order_id" db:"order_id" validate:""`
	Title string `json:"title" db:"title" validate:""`
	Content string `json:"content" db:"content" validate:""`
	Rating int32 `json:"rating" db:"rating" validate:""`
	IsVerifiedPurchase bool `json:"is_verified_purchase" db:"is_verified_purchase" validate:""`
	Status string `json:"status" db:"status" validate:""`
	IsFeatured bool `json:"is_featured" db:"is_featured" validate:""`
	HelpfulCount int32 `json:"helpful_count" db:"helpful_count" validate:""`
	NotHelpfulCount int32 `json:"not_helpful_count" db:"not_helpful_count" validate:""`
	MerchantResponse string `json:"merchant_response" db:"merchant_response" validate:""`
	MerchantResponseAt time.Time `json:"merchant_response_at" db:"merchant_response_at" validate:""`
	MerchantResponseByUserId int64 `json:"merchant_response_by_user_id" db:"merchant_response_by_user_id" validate:""`
	ReportCount int32 `json:"report_count" db:"report_count" validate:""`
	ReportReasons string `json:"report_reasons" db:"report_reasons" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
	ApprovedAt time.Time `json:"approved_at" db:"approved_at" validate:""`
}

// Validate validates the Review model
func (m *Review) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// ReviewObjects provides type-safe operations for Review
// Uses generic orm.Manager[Review] and orm.BaseQuerySet[Review]
var ReviewObjects, _ = orm.NewManager[Review]("reviews")

// ReviewFields provides type-safe field access for Review
type ReviewFields struct {
	Id orm.Field[int64]
	ProductId orm.Field[int64]
	CustomerId orm.Field[int64]
	OrderId orm.Field[int64]
	Title orm.Field[string]
	Content orm.Field[string]
	Rating orm.Field[int32]
	IsVerifiedPurchase orm.Field[bool]
	Status orm.Field[string]
	IsFeatured orm.Field[bool]
	HelpfulCount orm.Field[int32]
	NotHelpfulCount orm.Field[int32]
	MerchantResponse orm.Field[string]
	MerchantResponseAt orm.Field[time.Time]
	MerchantResponseByUserId orm.Field[int64]
	ReportCount orm.Field[int32]
	ReportReasons orm.Field[string]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
	ApprovedAt orm.Field[time.Time]
}

var ReviewFieldsInstance = ReviewFields{
	Id: orm.NewField[int64]("id", "reviews"),
	ProductId: orm.NewField[int64]("product_id", "reviews"),
	CustomerId: orm.NewField[int64]("customer_id", "reviews"),
	OrderId: orm.NewField[int64]("order_id", "reviews"),
	Title: orm.NewField[string]("title", "reviews"),
	Content: orm.NewField[string]("content", "reviews"),
	Rating: orm.NewField[int32]("rating", "reviews"),
	IsVerifiedPurchase: orm.NewField[bool]("is_verified_purchase", "reviews"),
	Status: orm.NewField[string]("status", "reviews"),
	IsFeatured: orm.NewField[bool]("is_featured", "reviews"),
	HelpfulCount: orm.NewField[int32]("helpful_count", "reviews"),
	NotHelpfulCount: orm.NewField[int32]("not_helpful_count", "reviews"),
	MerchantResponse: orm.NewField[string]("merchant_response", "reviews"),
	MerchantResponseAt: orm.NewField[time.Time]("merchant_response_at", "reviews"),
	MerchantResponseByUserId: orm.NewField[int64]("merchant_response_by_user_id", "reviews"),
	ReportCount: orm.NewField[int32]("report_count", "reviews"),
	ReportReasons: orm.NewField[string]("report_reasons", "reviews"),
	CreatedAt: orm.NewField[time.Time]("created_at", "reviews"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "reviews"),
	ApprovedAt: orm.NewField[time.Time]("approved_at", "reviews"),
}




// ReviewImageGenerated struct definition
type ReviewImageGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	ReviewId int64 `json:"review_id" db:"review_id" validate:""`
	ImageUrl string `json:"image_url" db:"image_url" validate:""`
	ThumbnailUrl string `json:"thumbnail_url" db:"thumbnail_url" validate:""`
	AltText string `json:"alt_text" db:"alt_text" validate:""`
	SortOrder int32 `json:"sort_order" db:"sort_order" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
}

// Validate validates the ReviewImage model
func (m *ReviewImage) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// ReviewImageObjects provides type-safe operations for ReviewImage
// Uses generic orm.Manager[ReviewImage] and orm.BaseQuerySet[ReviewImage]
var ReviewImageObjects, _ = orm.NewManager[ReviewImage]("review_images")

// ReviewImageFields provides type-safe field access for ReviewImage
type ReviewImageFields struct {
	Id orm.Field[int64]
	ReviewId orm.Field[int64]
	ImageUrl orm.Field[string]
	ThumbnailUrl orm.Field[string]
	AltText orm.Field[string]
	SortOrder orm.Field[int32]
	CreatedAt orm.Field[time.Time]
}

var ReviewImageFieldsInstance = ReviewImageFields{
	Id: orm.NewField[int64]("id", "review_images"),
	ReviewId: orm.NewField[int64]("review_id", "review_images"),
	ImageUrl: orm.NewField[string]("image_url", "review_images"),
	ThumbnailUrl: orm.NewField[string]("thumbnail_url", "review_images"),
	AltText: orm.NewField[string]("alt_text", "review_images"),
	SortOrder: orm.NewField[int32]("sort_order", "review_images"),
	CreatedAt: orm.NewField[time.Time]("created_at", "review_images"),
}




// ReviewHelpfulnessGenerated struct definition
type ReviewHelpfulnessGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	ReviewId int64 `json:"review_id" db:"review_id" validate:""`
	CustomerId int64 `json:"customer_id" db:"customer_id" validate:""`
	IsHelpful bool `json:"is_helpful" db:"is_helpful" validate:""`
	IpAddress string `json:"ip_address" db:"ip_address" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
}

// Validate validates the ReviewHelpfulness model
func (m *ReviewHelpfulness) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// ReviewHelpfulnessObjects provides type-safe operations for ReviewHelpfulness
// Uses generic orm.Manager[ReviewHelpfulness] and orm.BaseQuerySet[ReviewHelpfulness]
var ReviewHelpfulnessObjects, _ = orm.NewManager[ReviewHelpfulness]("review_helpfulness")

// ReviewHelpfulnessFields provides type-safe field access for ReviewHelpfulness
type ReviewHelpfulnessFields struct {
	Id orm.Field[int64]
	ReviewId orm.Field[int64]
	CustomerId orm.Field[int64]
	IsHelpful orm.Field[bool]
	IpAddress orm.Field[string]
	CreatedAt orm.Field[time.Time]
}

var ReviewHelpfulnessFieldsInstance = ReviewHelpfulnessFields{
	Id: orm.NewField[int64]("id", "review_helpfulness"),
	ReviewId: orm.NewField[int64]("review_id", "review_helpfulness"),
	CustomerId: orm.NewField[int64]("customer_id", "review_helpfulness"),
	IsHelpful: orm.NewField[bool]("is_helpful", "review_helpfulness"),
	IpAddress: orm.NewField[string]("ip_address", "review_helpfulness"),
	CreatedAt: orm.NewField[time.Time]("created_at", "review_helpfulness"),
}




// ProductQuestionGenerated struct definition
type ProductQuestionGenerated struct {
	schema.BaseSchema
	Id int64 `json:"id" db:"id" validate:""`
	ProductId int64 `json:"product_id" db:"product_id" validate:""`
	CustomerId int64 `json:"customer_id" db:"customer_id" validate:""`
	Question string `json:"question" db:"question" validate:""`
	Answer string `json:"answer" db:"answer" validate:""`
	AnsweredAt time.Time `json:"answered_at" db:"answered_at" validate:""`
	AnsweredByUserId int64 `json:"answered_by_user_id" db:"answered_by_user_id" validate:""`
	AnsweredByUserName string `json:"answered_by_user_name" db:"answered_by_user_name" validate:""`
	Status string `json:"status" db:"status" validate:""`
	IsPublic bool `json:"is_public" db:"is_public" validate:""`
	HelpfulCount int32 `json:"helpful_count" db:"helpful_count" validate:""`
	CreatedAt time.Time `json:"created_at" db:"created_at" validate:""`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the ProductQuestion model
func (m *ProductQuestion) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// ProductQuestionObjects provides type-safe operations for ProductQuestion
// Uses generic orm.Manager[ProductQuestion] and orm.BaseQuerySet[ProductQuestion]
var ProductQuestionObjects, _ = orm.NewManager[ProductQuestion]("product_questions")

// ProductQuestionFields provides type-safe field access for ProductQuestion
type ProductQuestionFields struct {
	Id orm.Field[int64]
	ProductId orm.Field[int64]
	CustomerId orm.Field[int64]
	Question orm.Field[string]
	Answer orm.Field[string]
	AnsweredAt orm.Field[time.Time]
	AnsweredByUserId orm.Field[int64]
	AnsweredByUserName orm.Field[string]
	Status orm.Field[string]
	IsPublic orm.Field[bool]
	HelpfulCount orm.Field[int32]
	CreatedAt orm.Field[time.Time]
	UpdatedAt orm.Field[time.Time]
}

var ProductQuestionFieldsInstance = ProductQuestionFields{
	Id: orm.NewField[int64]("id", "product_questions"),
	ProductId: orm.NewField[int64]("product_id", "product_questions"),
	CustomerId: orm.NewField[int64]("customer_id", "product_questions"),
	Question: orm.NewField[string]("question", "product_questions"),
	Answer: orm.NewField[string]("answer", "product_questions"),
	AnsweredAt: orm.NewField[time.Time]("answered_at", "product_questions"),
	AnsweredByUserId: orm.NewField[int64]("answered_by_user_id", "product_questions"),
	AnsweredByUserName: orm.NewField[string]("answered_by_user_name", "product_questions"),
	Status: orm.NewField[string]("status", "product_questions"),
	IsPublic: orm.NewField[bool]("is_public", "product_questions"),
	HelpfulCount: orm.NewField[int32]("helpful_count", "product_questions"),
	CreatedAt: orm.NewField[time.Time]("created_at", "product_questions"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "product_questions"),
}




