name: avalai
version: 1.0.0
schema: v1

models:
  - name: avalai-deepseek
    provider: openai
    model: deepseek-reasoner
    apiBase: https://api.avalai.ir/v1
    apiKey: aa-Ra0anUEV1f9kfmfn0UuIeEC5AN0BsF9UskA9H1NL04A8uLiL
    roles:
      - chat
      - autocomplete
