/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelRouteRouteImport } from './routes/$model/route'
import { Route as FormPlaygroundRouteImport } from './routes/form-playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as ModelIndexRouteImport } from './routes/$model/index'
import { Route as ModelIdRouteImport } from './routes/$model/$id'
import { Route as ModelCreateRouteImport } from './routes/$model/create'
import { Route as ModelIdViewRouteImport } from './routes/$model/$id.view'
import { Route as PluginsPluginIdPagesPageIdRouteImport } from './routes/plugins/$pluginId/pages/$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRouteRoute = ModelRouteRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const FormPlaygroundRoute = FormPlaygroundRouteImport.update({
  id: '/form-playground',
  path: '/form-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelIndexRoute = ModelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelRouteRoute,
} as any)
const ModelIdRoute = ModelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ModelRouteRoute,
} as any)
const ModelCreateRoute = ModelCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ModelRouteRoute,
} as any)
const ModelIdViewRoute = ModelIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => ModelIdRoute,
} as any)
const PluginsPluginIdPagesPageIdRoute =
  PluginsPluginIdPagesPageIdRouteImport.update({
    id: '/plugins/$pluginId/pages/$pageId',
    path: '/plugins/$pluginId/pages/$pageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$model': typeof ModelRouteRouteWithChildren
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/style-guide': typeof StyleGuideRoute
  '/$model/$id': typeof ModelIdRouteWithChildren
  '/$model/create': typeof ModelCreateRoute
  '/$model/': typeof ModelIndexRoute
  '/$model/$id/view': typeof ModelIdViewRoute
  '/plugins/$pluginId/pages/$pageId': typeof PluginsPluginIdPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/style-guide': typeof StyleGuideRoute
  '/$model/$id': typeof ModelIdRouteWithChildren
  '/$model/create': typeof ModelCreateRoute
  '/$model': typeof ModelIndexRoute
  '/$model/$id/view': typeof ModelIdViewRoute
  '/plugins/$pluginId/pages/$pageId': typeof PluginsPluginIdPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$model': typeof ModelRouteRouteWithChildren
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/style-guide': typeof StyleGuideRoute
  '/$model/$id': typeof ModelIdRouteWithChildren
  '/$model/create': typeof ModelCreateRoute
  '/$model/': typeof ModelIndexRoute
  '/$model/$id/view': typeof ModelIdViewRoute
  '/plugins/$pluginId/pages/$pageId': typeof PluginsPluginIdPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$model'
    | '/form-playground'
    | '/login'
    | '/style-guide'
    | '/$model/$id'
    | '/$model/create'
    | '/$model/'
    | '/$model/$id/view'
    | '/plugins/$pluginId/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/form-playground'
    | '/login'
    | '/style-guide'
    | '/$model/$id'
    | '/$model/create'
    | '/$model'
    | '/$model/$id/view'
    | '/plugins/$pluginId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/$model'
    | '/form-playground'
    | '/login'
    | '/style-guide'
    | '/$model/$id'
    | '/$model/create'
    | '/$model/'
    | '/$model/$id/view'
    | '/plugins/$pluginId/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelRouteRoute: typeof ModelRouteRouteWithChildren
  FormPlaygroundRoute: typeof FormPlaygroundRoute
  LoginRoute: typeof LoginRoute
  StyleGuideRoute: typeof StyleGuideRoute
  PluginsPluginIdPagesPageIdRoute: typeof PluginsPluginIdPagesPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$model': {
      id: '/$model'
      path: '/$model'
      fullPath: '/$model'
      preLoaderRoute: typeof ModelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-playground': {
      id: '/form-playground'
      path: '/form-playground'
      fullPath: '/form-playground'
      preLoaderRoute: typeof FormPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$model/': {
      id: '/$model/'
      path: '/'
      fullPath: '/$model/'
      preLoaderRoute: typeof ModelIndexRouteImport
      parentRoute: typeof ModelRouteRoute
    }
    '/$model/$id': {
      id: '/$model/$id'
      path: '/$id'
      fullPath: '/$model/$id'
      preLoaderRoute: typeof ModelIdRouteImport
      parentRoute: typeof ModelRouteRoute
    }
    '/$model/create': {
      id: '/$model/create'
      path: '/create'
      fullPath: '/$model/create'
      preLoaderRoute: typeof ModelCreateRouteImport
      parentRoute: typeof ModelRouteRoute
    }
    '/$model/$id/view': {
      id: '/$model/$id/view'
      path: '/view'
      fullPath: '/$model/$id/view'
      preLoaderRoute: typeof ModelIdViewRouteImport
      parentRoute: typeof ModelIdRoute
    }
    '/plugins/$pluginId/pages/$pageId': {
      id: '/plugins/$pluginId/pages/$pageId'
      path: '/plugins/$pluginId/pages/$pageId'
      fullPath: '/plugins/$pluginId/pages/$pageId'
      preLoaderRoute: typeof PluginsPluginIdPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ModelIdRouteChildren {
  ModelIdViewRoute: typeof ModelIdViewRoute
}

const ModelIdRouteChildren: ModelIdRouteChildren = {
  ModelIdViewRoute: ModelIdViewRoute,
}

const ModelIdRouteWithChildren =
  ModelIdRoute._addFileChildren(ModelIdRouteChildren)

interface ModelRouteRouteChildren {
  ModelIdRoute: typeof ModelIdRouteWithChildren
  ModelCreateRoute: typeof ModelCreateRoute
  ModelIndexRoute: typeof ModelIndexRoute
}

const ModelRouteRouteChildren: ModelRouteRouteChildren = {
  ModelIdRoute: ModelIdRouteWithChildren,
  ModelCreateRoute: ModelCreateRoute,
  ModelIndexRoute: ModelIndexRoute,
}

const ModelRouteRouteWithChildren = ModelRouteRoute._addFileChildren(
  ModelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelRouteRoute: ModelRouteRouteWithChildren,
  FormPlaygroundRoute: FormPlaygroundRoute,
  LoginRoute: LoginRoute,
  StyleGuideRoute: StyleGuideRoute,
  PluginsPluginIdPagesPageIdRoute: PluginsPluginIdPagesPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
