// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as LoginRoute } from './routes/login';
import { Route as AdminModelRoute } from './routes/admin/$model';
import { Route as AdminModelNewRoute } from './routes/admin/$model.new';
import { Route as AdminModelIdRoute } from './routes/admin/$model.$id';
import { Route as PagesPageRoute } from './routes/pages/$page';

// Create/Update Routes
const LoginRouteRoute = LoginRoute.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const AdminModelRouteRoute = AdminModelRoute.update({
  path: '/$model',
  getParentRoute: () => rootRoute,
} as any);

const AdminModelNewRouteRoute = AdminModelNewRoute.update({
  path: '/$model/new',
  getParentRoute: () => rootRoute,
} as any);

const AdminModelIdRouteRoute = AdminModelIdRoute.update({
  path: '/$model/$id',
  getParentRoute: () => rootRoute,
} as any);

const PagesPageRouteRoute = PagesPageRoute.update({
  path: '/pages/$page',
  getParentRoute: () => rootRoute,
} as any);

const IndexRouteRoute = IndexRoute.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRouteRoute;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      preLoaderRoute: typeof LoginRouteRoute;
      parentRoute: typeof rootRoute;
    };
    '/$model': {
      preLoaderRoute: typeof AdminModelRouteRoute;
      parentRoute: typeof rootRoute;
    };
    '/$model/new': {
      preLoaderRoute: typeof AdminModelNewRouteRoute;
      parentRoute: typeof rootRoute;
    };
    '/$model/$id': {
      preLoaderRoute: typeof AdminModelIdRouteRoute;
      parentRoute: typeof rootRoute;
    };
    '/pages/$page': {
      preLoaderRoute: typeof PagesPageRouteRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree
export const routeTree = rootRoute.addChildren([
  IndexRouteRoute,
  LoginRouteRoute,
  AdminModelNewRouteRoute,
  AdminModelIdRouteRoute,
  AdminModelRouteRoute,
  PagesPageRouteRoute,
]);
