// Code generated by forge. DO NOT EDIT.
package trading

import (
	"time"

	"github.com/forgego/forge/orm"
	validation "github.com/forgego/forge/validate"
)

// Validate validates the Order model
func (m *Order) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// OrderObjects provides type-safe operations for Order
// Uses generic orm.Manager[Order] and orm.BaseQuerySet[Order]
var OrderObjects, _ = orm.NewManager[Order]("orders")

func init() {
	if OrderObjects != nil {
		orm.RegisterManagerFor[Order](OrderObjects)
	}
}

// OrderFields provides type-safe field access for Order
type OrderFields struct {
	Id             orm.FieldExpression[int64]
	UserId         orm.FieldExpression[int64]
	PairId         orm.FieldExpression[int64]
	Side           orm.FieldExpression[string]
	OrderType      orm.FieldExpression[string]
	Status         orm.FieldExpression[string]
	Price          orm.FieldExpression[float64]
	Quantity       orm.FieldExpression[float64]
	FilledQuantity orm.FieldExpression[float64]
	CreatedAt      orm.FieldExpression[time.Time]
	UpdatedAt      orm.FieldExpression[time.Time]
}

var OrderFieldsInstance = OrderFields{
	Id:             orm.NewField[int64]("id", "orders"),
	UserId:         orm.NewField[int64]("user_id", "orders"),
	PairId:         orm.NewField[int64]("pair_id", "orders"),
	Side:           orm.NewField[string]("side", "orders"),
	OrderType:      orm.NewField[string]("order_type", "orders"),
	Status:         orm.NewField[string]("status", "orders"),
	Price:          orm.NewField[float64]("price", "orders"),
	Quantity:       orm.NewField[float64]("quantity", "orders"),
	FilledQuantity: orm.NewField[float64]("filled_quantity", "orders"),
	CreatedAt:      orm.NewField[time.Time]("created_at", "orders"),
	UpdatedAt:      orm.NewField[time.Time]("updated_at", "orders"),
}

// Validate validates the Trade model
func (m *Trade) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// TradeObjects provides type-safe operations for Trade
// Uses generic orm.Manager[Trade] and orm.BaseQuerySet[Trade]
var TradeObjects, _ = orm.NewManager[Trade]("trades")

func init() {
	if TradeObjects != nil {
		orm.RegisterManagerFor[Trade](TradeObjects)
	}
}

// TradeFields provides type-safe field access for Trade
type TradeFields struct {
	Id          orm.FieldExpression[int64]
	PairId      orm.FieldExpression[int64]
	BuyOrderId  orm.FieldExpression[int64]
	SellOrderId orm.FieldExpression[int64]
	Price       orm.FieldExpression[float64]
	Quantity    orm.FieldExpression[float64]
	ExecutedAt  orm.FieldExpression[time.Time]
}

var TradeFieldsInstance = TradeFields{
	Id:          orm.NewField[int64]("id", "trades"),
	PairId:      orm.NewField[int64]("pair_id", "trades"),
	BuyOrderId:  orm.NewField[int64]("buy_order_id", "trades"),
	SellOrderId: orm.NewField[int64]("sell_order_id", "trades"),
	Price:       orm.NewField[float64]("price", "trades"),
	Quantity:    orm.NewField[float64]("quantity", "trades"),
	ExecutedAt:  orm.NewField[time.Time]("executed_at", "trades"),
}
