// Code generated by forge. DO NOT EDIT.
package inventory

import (
	"time"
	"github.com/forgego/forge/orm"
	"github.com/forgego/forge/schema"
	"github.com/forgego/forge/validate"
)


// WarehouseGenerated struct definition
type WarehouseGenerated struct {
	schema.BaseSchema
	id int64 `json:"id" db:"id" validate:""`
	name string `json:"name" db:"name" validate:""`
	code string `json:"code" db:"code" validate:""`
	contact_name string `json:"contact_name" db:"contact_name" validate:""`
	contact_email string `json:"contact_email" db:"contact_email" validate:""`
	contact_phone string `json:"contact_phone" db:"contact_phone" validate:""`
	address_line1 string `json:"address_line1" db:"address_line1" validate:""`
	address_line2 string `json:"address_line2" db:"address_line2" validate:""`
	city string `json:"city" db:"city" validate:""`
	state string `json:"state" db:"state" validate:""`
	postal_code string `json:"postal_code" db:"postal_code" validate:""`
	country_code string `json:"country_code" db:"country_code" validate:""`
	country_name string `json:"country_name" db:"country_name" validate:""`
	latitude float64 `json:"latitude" db:"latitude" validate:""`
	longitude float64 `json:"longitude" db:"longitude" validate:""`
	is_active bool `json:"is_active" db:"is_active" validate:""`
	is_primary bool `json:"is_primary" db:"is_primary" validate:""`
	priority int32 `json:"priority" db:"priority" validate:""`
	total_capacity int32 `json:"total_capacity" db:"total_capacity" validate:""`
	created_at time.Time `json:"created_at" db:"created_at" validate:""`
	updated_at time.Time `json:"updated_at" db:"updated_at" validate:""`
}

// Validate validates the Warehouse model
func (m *Warehouse) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// WarehouseObjects provides type-safe operations for Warehouse
// Uses generic orm.Manager[Warehouse] and orm.BaseQuerySet[Warehouse]
var WarehouseObjects, _ = orm.NewManager[Warehouse]("warehouses")

// WarehouseFields provides type-safe field access for Warehouse
type WarehouseFields struct {
	id orm.Field[int64]
	name orm.Field[string]
	code orm.Field[string]
	contact_name orm.Field[string]
	contact_email orm.Field[string]
	contact_phone orm.Field[string]
	address_line1 orm.Field[string]
	address_line2 orm.Field[string]
	city orm.Field[string]
	state orm.Field[string]
	postal_code orm.Field[string]
	country_code orm.Field[string]
	country_name orm.Field[string]
	latitude orm.Field[float64]
	longitude orm.Field[float64]
	is_active orm.Field[bool]
	is_primary orm.Field[bool]
	priority orm.Field[int32]
	total_capacity orm.Field[int32]
	created_at orm.Field[time.Time]
	updated_at orm.Field[time.Time]
}

var WarehouseFields = WarehouseFields{
	id: orm.NewField[int64]("id", "warehouses"),
	name: orm.NewField[string]("name", "warehouses"),
	code: orm.NewField[string]("code", "warehouses"),
	contact_name: orm.NewField[string]("contact_name", "warehouses"),
	contact_email: orm.NewField[string]("contact_email", "warehouses"),
	contact_phone: orm.NewField[string]("contact_phone", "warehouses"),
	address_line1: orm.NewField[string]("address_line1", "warehouses"),
	address_line2: orm.NewField[string]("address_line2", "warehouses"),
	city: orm.NewField[string]("city", "warehouses"),
	state: orm.NewField[string]("state", "warehouses"),
	postal_code: orm.NewField[string]("postal_code", "warehouses"),
	country_code: orm.NewField[string]("country_code", "warehouses"),
	country_name: orm.NewField[string]("country_name", "warehouses"),
	latitude: orm.NewField[float64]("latitude", "warehouses"),
	longitude: orm.NewField[float64]("longitude", "warehouses"),
	is_active: orm.NewField[bool]("is_active", "warehouses"),
	is_primary: orm.NewField[bool]("is_primary", "warehouses"),
	priority: orm.NewField[int32]("priority", "warehouses"),
	total_capacity: orm.NewField[int32]("total_capacity", "warehouses"),
	created_at: orm.NewField[time.Time]("created_at", "warehouses"),
	updated_at: orm.NewField[time.Time]("updated_at", "warehouses"),
}




// StockGenerated struct definition
type StockGenerated struct {
	schema.BaseSchema
	id int64 `json:"id" db:"id" validate:""`
	product_variant_id int64 `json:"product_variant_id" db:"product_variant_id" validate:""`
	warehouse_id int64 `json:"warehouse_id" db:"warehouse_id" validate:""`
	quantity int32 `json:"quantity" db:"quantity" validate:""`
	reserved_quantity int32 `json:"reserved_quantity" db:"reserved_quantity" validate:""`
	available_quantity int32 `json:"available_quantity" db:"available_quantity" validate:""`
	reorder_point int32 `json:"reorder_point" db:"reorder_point" validate:""`
	reorder_quantity int32 `json:"reorder_quantity" db:"reorder_quantity" validate:""`
	bin_location string `json:"bin_location" db:"bin_location" validate:""`
	is_active bool `json:"is_active" db:"is_active" validate:""`
	allow_backorder bool `json:"allow_backorder" db:"allow_backorder" validate:""`
	created_at time.Time `json:"created_at" db:"created_at" validate:""`
	updated_at time.Time `json:"updated_at" db:"updated_at" validate:""`
	last_counted_at time.Time `json:"last_counted_at" db:"last_counted_at" validate:""`
}

// Validate validates the Stock model
func (m *Stock) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// StockObjects provides type-safe operations for Stock
// Uses generic orm.Manager[Stock] and orm.BaseQuerySet[Stock]
var StockObjects, _ = orm.NewManager[Stock]("stock")

// StockFields provides type-safe field access for Stock
type StockFields struct {
	id orm.Field[int64]
	product_variant_id orm.Field[int64]
	warehouse_id orm.Field[int64]
	quantity orm.Field[int32]
	reserved_quantity orm.Field[int32]
	available_quantity orm.Field[int32]
	reorder_point orm.Field[int32]
	reorder_quantity orm.Field[int32]
	bin_location orm.Field[string]
	is_active orm.Field[bool]
	allow_backorder orm.Field[bool]
	created_at orm.Field[time.Time]
	updated_at orm.Field[time.Time]
	last_counted_at orm.Field[time.Time]
}

var StockFields = StockFields{
	id: orm.NewField[int64]("id", "stock"),
	product_variant_id: orm.NewField[int64]("product_variant_id", "stock"),
	warehouse_id: orm.NewField[int64]("warehouse_id", "stock"),
	quantity: orm.NewField[int32]("quantity", "stock"),
	reserved_quantity: orm.NewField[int32]("reserved_quantity", "stock"),
	available_quantity: orm.NewField[int32]("available_quantity", "stock"),
	reorder_point: orm.NewField[int32]("reorder_point", "stock"),
	reorder_quantity: orm.NewField[int32]("reorder_quantity", "stock"),
	bin_location: orm.NewField[string]("bin_location", "stock"),
	is_active: orm.NewField[bool]("is_active", "stock"),
	allow_backorder: orm.NewField[bool]("allow_backorder", "stock"),
	created_at: orm.NewField[time.Time]("created_at", "stock"),
	updated_at: orm.NewField[time.Time]("updated_at", "stock"),
	last_counted_at: orm.NewField[time.Time]("last_counted_at", "stock"),
}




// StockMovementGenerated struct definition
type StockMovementGenerated struct {
	schema.BaseSchema
	id int64 `json:"id" db:"id" validate:""`
	stock_id int64 `json:"stock_id" db:"stock_id" validate:""`
	product_variant_id int64 `json:"product_variant_id" db:"product_variant_id" validate:""`
	warehouse_id int64 `json:"warehouse_id" db:"warehouse_id" validate:""`
	type string `json:"type" db:"type" validate:""`
	quantity int32 `json:"quantity" db:"quantity" validate:""`
	quantity_before int32 `json:"quantity_before" db:"quantity_before" validate:""`
	quantity_after int32 `json:"quantity_after" db:"quantity_after" validate:""`
	reference_type string `json:"reference_type" db:"reference_type" validate:""`
	reference_id int64 `json:"reference_id" db:"reference_id" validate:""`
	reference_number string `json:"reference_number" db:"reference_number" validate:""`
	from_warehouse_id int64 `json:"from_warehouse_id" db:"from_warehouse_id" validate:""`
	to_warehouse_id int64 `json:"to_warehouse_id" db:"to_warehouse_id" validate:""`
	reason string `json:"reason" db:"reason" validate:""`
	notes string `json:"notes" db:"notes" validate:""`
	user_id int64 `json:"user_id" db:"user_id" validate:""`
	user_name string `json:"user_name" db:"user_name" validate:""`
	unit_cost float64 `json:"unit_cost" db:"unit_cost" validate:""`
	total_cost float64 `json:"total_cost" db:"total_cost" validate:""`
	created_at time.Time `json:"created_at" db:"created_at" validate:""`
	movement_date time.Time `json:"movement_date" db:"movement_date" validate:""`
}

// Validate validates the StockMovement model
func (m *StockMovement) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// StockMovementObjects provides type-safe operations for StockMovement
// Uses generic orm.Manager[StockMovement] and orm.BaseQuerySet[StockMovement]
var StockMovementObjects, _ = orm.NewManager[StockMovement]("stock_movements")

// StockMovementFields provides type-safe field access for StockMovement
type StockMovementFields struct {
	id orm.Field[int64]
	stock_id orm.Field[int64]
	product_variant_id orm.Field[int64]
	warehouse_id orm.Field[int64]
	type orm.Field[string]
	quantity orm.Field[int32]
	quantity_before orm.Field[int32]
	quantity_after orm.Field[int32]
	reference_type orm.Field[string]
	reference_id orm.Field[int64]
	reference_number orm.Field[string]
	from_warehouse_id orm.Field[int64]
	to_warehouse_id orm.Field[int64]
	reason orm.Field[string]
	notes orm.Field[string]
	user_id orm.Field[int64]
	user_name orm.Field[string]
	unit_cost orm.Field[float64]
	total_cost orm.Field[float64]
	created_at orm.Field[time.Time]
	movement_date orm.Field[time.Time]
}

var StockMovementFields = StockMovementFields{
	id: orm.NewField[int64]("id", "stock_movements"),
	stock_id: orm.NewField[int64]("stock_id", "stock_movements"),
	product_variant_id: orm.NewField[int64]("product_variant_id", "stock_movements"),
	warehouse_id: orm.NewField[int64]("warehouse_id", "stock_movements"),
	type: orm.NewField[string]("type", "stock_movements"),
	quantity: orm.NewField[int32]("quantity", "stock_movements"),
	quantity_before: orm.NewField[int32]("quantity_before", "stock_movements"),
	quantity_after: orm.NewField[int32]("quantity_after", "stock_movements"),
	reference_type: orm.NewField[string]("reference_type", "stock_movements"),
	reference_id: orm.NewField[int64]("reference_id", "stock_movements"),
	reference_number: orm.NewField[string]("reference_number", "stock_movements"),
	from_warehouse_id: orm.NewField[int64]("from_warehouse_id", "stock_movements"),
	to_warehouse_id: orm.NewField[int64]("to_warehouse_id", "stock_movements"),
	reason: orm.NewField[string]("reason", "stock_movements"),
	notes: orm.NewField[string]("notes", "stock_movements"),
	user_id: orm.NewField[int64]("user_id", "stock_movements"),
	user_name: orm.NewField[string]("user_name", "stock_movements"),
	unit_cost: orm.NewField[float64]("unit_cost", "stock_movements"),
	total_cost: orm.NewField[float64]("total_cost", "stock_movements"),
	created_at: orm.NewField[time.Time]("created_at", "stock_movements"),
	movement_date: orm.NewField[time.Time]("movement_date", "stock_movements"),
}




// StockAlertGenerated struct definition
type StockAlertGenerated struct {
	schema.BaseSchema
	id int64 `json:"id" db:"id" validate:""`
	stock_id int64 `json:"stock_id" db:"stock_id" validate:""`
	product_variant_id int64 `json:"product_variant_id" db:"product_variant_id" validate:""`
	warehouse_id int64 `json:"warehouse_id" db:"warehouse_id" validate:""`
	alert_type string `json:"alert_type" db:"alert_type" validate:""`
	current_quantity int32 `json:"current_quantity" db:"current_quantity" validate:""`
	threshold int32 `json:"threshold" db:"threshold" validate:""`
	status string `json:"status" db:"status" validate:""`
	resolved_by_user_id int64 `json:"resolved_by_user_id" db:"resolved_by_user_id" validate:""`
	resolved_by_user_name string `json:"resolved_by_user_name" db:"resolved_by_user_name" validate:""`
	resolution_notes string `json:"resolution_notes" db:"resolution_notes" validate:""`
	notification_sent bool `json:"notification_sent" db:"notification_sent" validate:""`
	notification_sent_at time.Time `json:"notification_sent_at" db:"notification_sent_at" validate:""`
	created_at time.Time `json:"created_at" db:"created_at" validate:""`
	updated_at time.Time `json:"updated_at" db:"updated_at" validate:""`
	acknowledged_at time.Time `json:"acknowledged_at" db:"acknowledged_at" validate:""`
	resolved_at time.Time `json:"resolved_at" db:"resolved_at" validate:""`
}

// Validate validates the StockAlert model
func (m *StockAlert) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// StockAlertObjects provides type-safe operations for StockAlert
// Uses generic orm.Manager[StockAlert] and orm.BaseQuerySet[StockAlert]
var StockAlertObjects, _ = orm.NewManager[StockAlert]("stock_alerts")

// StockAlertFields provides type-safe field access for StockAlert
type StockAlertFields struct {
	id orm.Field[int64]
	stock_id orm.Field[int64]
	product_variant_id orm.Field[int64]
	warehouse_id orm.Field[int64]
	alert_type orm.Field[string]
	current_quantity orm.Field[int32]
	threshold orm.Field[int32]
	status orm.Field[string]
	resolved_by_user_id orm.Field[int64]
	resolved_by_user_name orm.Field[string]
	resolution_notes orm.Field[string]
	notification_sent orm.Field[bool]
	notification_sent_at orm.Field[time.Time]
	created_at orm.Field[time.Time]
	updated_at orm.Field[time.Time]
	acknowledged_at orm.Field[time.Time]
	resolved_at orm.Field[time.Time]
}

var StockAlertFields = StockAlertFields{
	id: orm.NewField[int64]("id", "stock_alerts"),
	stock_id: orm.NewField[int64]("stock_id", "stock_alerts"),
	product_variant_id: orm.NewField[int64]("product_variant_id", "stock_alerts"),
	warehouse_id: orm.NewField[int64]("warehouse_id", "stock_alerts"),
	alert_type: orm.NewField[string]("alert_type", "stock_alerts"),
	current_quantity: orm.NewField[int32]("current_quantity", "stock_alerts"),
	threshold: orm.NewField[int32]("threshold", "stock_alerts"),
	status: orm.NewField[string]("status", "stock_alerts"),
	resolved_by_user_id: orm.NewField[int64]("resolved_by_user_id", "stock_alerts"),
	resolved_by_user_name: orm.NewField[string]("resolved_by_user_name", "stock_alerts"),
	resolution_notes: orm.NewField[string]("resolution_notes", "stock_alerts"),
	notification_sent: orm.NewField[bool]("notification_sent", "stock_alerts"),
	notification_sent_at: orm.NewField[time.Time]("notification_sent_at", "stock_alerts"),
	created_at: orm.NewField[time.Time]("created_at", "stock_alerts"),
	updated_at: orm.NewField[time.Time]("updated_at", "stock_alerts"),
	acknowledged_at: orm.NewField[time.Time]("acknowledged_at", "stock_alerts"),
	resolved_at: orm.NewField[time.Time]("resolved_at", "stock_alerts"),
}




// StockTransferGenerated struct definition
type StockTransferGenerated struct {
	schema.BaseSchema
	id int64 `json:"id" db:"id" validate:""`
	transfer_number string `json:"transfer_number" db:"transfer_number" validate:""`
	from_warehouse_id int64 `json:"from_warehouse_id" db:"from_warehouse_id" validate:""`
	to_warehouse_id int64 `json:"to_warehouse_id" db:"to_warehouse_id" validate:""`
	product_variant_id int64 `json:"product_variant_id" db:"product_variant_id" validate:""`
	quantity int32 `json:"quantity" db:"quantity" validate:""`
	status string `json:"status" db:"status" validate:""`
	tracking_number string `json:"tracking_number" db:"tracking_number" validate:""`
	carrier string `json:"carrier" db:"carrier" validate:""`
	notes string `json:"notes" db:"notes" validate:""`
	reason string `json:"reason" db:"reason" validate:""`
	requested_by_user_id int64 `json:"requested_by_user_id" db:"requested_by_user_id" validate:""`
	requested_by_user_name string `json:"requested_by_user_name" db:"requested_by_user_name" validate:""`
	approved_by_user_id int64 `json:"approved_by_user_id" db:"approved_by_user_id" validate:""`
	approved_by_user_name string `json:"approved_by_user_name" db:"approved_by_user_name" validate:""`
	created_at time.Time `json:"created_at" db:"created_at" validate:""`
	updated_at time.Time `json:"updated_at" db:"updated_at" validate:""`
	shipped_at time.Time `json:"shipped_at" db:"shipped_at" validate:""`
	completed_at time.Time `json:"completed_at" db:"completed_at" validate:""`
	cancelled_at time.Time `json:"cancelled_at" db:"cancelled_at" validate:""`
}

// Validate validates the StockTransfer model
func (m *StockTransfer) Validate() error {
	validator := validate.NewValidator()
	return validate.ValidateModel(validator, m)
}

// StockTransferObjects provides type-safe operations for StockTransfer
// Uses generic orm.Manager[StockTransfer] and orm.BaseQuerySet[StockTransfer]
var StockTransferObjects, _ = orm.NewManager[StockTransfer]("stock_transfers")

// StockTransferFields provides type-safe field access for StockTransfer
type StockTransferFields struct {
	id orm.Field[int64]
	transfer_number orm.Field[string]
	from_warehouse_id orm.Field[int64]
	to_warehouse_id orm.Field[int64]
	product_variant_id orm.Field[int64]
	quantity orm.Field[int32]
	status orm.Field[string]
	tracking_number orm.Field[string]
	carrier orm.Field[string]
	notes orm.Field[string]
	reason orm.Field[string]
	requested_by_user_id orm.Field[int64]
	requested_by_user_name orm.Field[string]
	approved_by_user_id orm.Field[int64]
	approved_by_user_name orm.Field[string]
	created_at orm.Field[time.Time]
	updated_at orm.Field[time.Time]
	shipped_at orm.Field[time.Time]
	completed_at orm.Field[time.Time]
	cancelled_at orm.Field[time.Time]
}

var StockTransferFields = StockTransferFields{
	id: orm.NewField[int64]("id", "stock_transfers"),
	transfer_number: orm.NewField[string]("transfer_number", "stock_transfers"),
	from_warehouse_id: orm.NewField[int64]("from_warehouse_id", "stock_transfers"),
	to_warehouse_id: orm.NewField[int64]("to_warehouse_id", "stock_transfers"),
	product_variant_id: orm.NewField[int64]("product_variant_id", "stock_transfers"),
	quantity: orm.NewField[int32]("quantity", "stock_transfers"),
	status: orm.NewField[string]("status", "stock_transfers"),
	tracking_number: orm.NewField[string]("tracking_number", "stock_transfers"),
	carrier: orm.NewField[string]("carrier", "stock_transfers"),
	notes: orm.NewField[string]("notes", "stock_transfers"),
	reason: orm.NewField[string]("reason", "stock_transfers"),
	requested_by_user_id: orm.NewField[int64]("requested_by_user_id", "stock_transfers"),
	requested_by_user_name: orm.NewField[string]("requested_by_user_name", "stock_transfers"),
	approved_by_user_id: orm.NewField[int64]("approved_by_user_id", "stock_transfers"),
	approved_by_user_name: orm.NewField[string]("approved_by_user_name", "stock_transfers"),
	created_at: orm.NewField[time.Time]("created_at", "stock_transfers"),
	updated_at: orm.NewField[time.Time]("updated_at", "stock_transfers"),
	shipped_at: orm.NewField[time.Time]("shipped_at", "stock_transfers"),
	completed_at: orm.NewField[time.Time]("completed_at", "stock_transfers"),
	cancelled_at: orm.NewField[time.Time]("cancelled_at", "stock_transfers"),
}




