// Code generated by forge. DO NOT EDIT.
package inventory

import (
	"time"
	"github.com/forgego/forge/orm"
	"github.com/forgego/forge/schema"
	"github.com/forgego/forge/validate"
)



// Validate validates the Warehouse model
func (m *Warehouse) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// WarehouseObjects provides type-safe operations for Warehouse
// Uses generic orm.Manager[Warehouse] and orm.BaseQuerySet[Warehouse]
var WarehouseObjects, _ = orm.NewManager[Warehouse]("warehouses")

// WarehouseFields provides type-safe field access for Warehouse
type WarehouseFields struct {
	Id orm.FieldExpression[int64]
	Name orm.FieldExpression[string]
	Code orm.FieldExpression[string]
	ContactName orm.FieldExpression[string]
	ContactEmail orm.FieldExpression[string]
	ContactPhone orm.FieldExpression[string]
	AddressLine1 orm.FieldExpression[string]
	AddressLine2 orm.FieldExpression[string]
	City orm.FieldExpression[string]
	State orm.FieldExpression[string]
	PostalCode orm.FieldExpression[string]
	CountryCode orm.FieldExpression[string]
	CountryName orm.FieldExpression[string]
	Latitude orm.FieldExpression[float64]
	Longitude orm.FieldExpression[float64]
	IsActive orm.FieldExpression[bool]
	IsPrimary orm.FieldExpression[bool]
	Priority orm.FieldExpression[int32]
	TotalCapacity orm.FieldExpression[int32]
	CreatedAt orm.FieldExpression[time.Time]
	UpdatedAt orm.FieldExpression[time.Time]
}

var WarehouseFieldsInstance = WarehouseFields{
	Id: orm.NewField[int64]("id", "warehouses"),
	Name: orm.NewField[string]("name", "warehouses"),
	Code: orm.NewField[string]("code", "warehouses"),
	ContactName: orm.NewField[string]("contact_name", "warehouses"),
	ContactEmail: orm.NewField[string]("contact_email", "warehouses"),
	ContactPhone: orm.NewField[string]("contact_phone", "warehouses"),
	AddressLine1: orm.NewField[string]("address_line1", "warehouses"),
	AddressLine2: orm.NewField[string]("address_line2", "warehouses"),
	City: orm.NewField[string]("city", "warehouses"),
	State: orm.NewField[string]("state", "warehouses"),
	PostalCode: orm.NewField[string]("postal_code", "warehouses"),
	CountryCode: orm.NewField[string]("country_code", "warehouses"),
	CountryName: orm.NewField[string]("country_name", "warehouses"),
	Latitude: orm.NewField[float64]("latitude", "warehouses"),
	Longitude: orm.NewField[float64]("longitude", "warehouses"),
	IsActive: orm.NewField[bool]("is_active", "warehouses"),
	IsPrimary: orm.NewField[bool]("is_primary", "warehouses"),
	Priority: orm.NewField[int32]("priority", "warehouses"),
	TotalCapacity: orm.NewField[int32]("total_capacity", "warehouses"),
	CreatedAt: orm.NewField[time.Time]("created_at", "warehouses"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "warehouses"),
}



// Validate validates the Stock model
func (m *Stock) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// StockObjects provides type-safe operations for Stock
// Uses generic orm.Manager[Stock] and orm.BaseQuerySet[Stock]
var StockObjects, _ = orm.NewManager[Stock]("stock")

// StockFields provides type-safe field access for Stock
type StockFields struct {
	Id orm.FieldExpression[int64]
	ProductVariantId orm.FieldExpression[int64]
	WarehouseId orm.FieldExpression[int64]
	Quantity orm.FieldExpression[int32]
	ReservedQuantity orm.FieldExpression[int32]
	AvailableQuantity orm.FieldExpression[int32]
	ReorderPoint orm.FieldExpression[int32]
	ReorderQuantity orm.FieldExpression[int32]
	BinLocation orm.FieldExpression[string]
	IsActive orm.FieldExpression[bool]
	AllowBackorder orm.FieldExpression[bool]
	CreatedAt orm.FieldExpression[time.Time]
	UpdatedAt orm.FieldExpression[time.Time]
	LastCountedAt orm.FieldExpression[time.Time]
}

var StockFieldsInstance = StockFields{
	Id: orm.NewField[int64]("id", "stock"),
	ProductVariantId: orm.NewField[int64]("product_variant_id", "stock"),
	WarehouseId: orm.NewField[int64]("warehouse_id", "stock"),
	Quantity: orm.NewField[int32]("quantity", "stock"),
	ReservedQuantity: orm.NewField[int32]("reserved_quantity", "stock"),
	AvailableQuantity: orm.NewField[int32]("available_quantity", "stock"),
	ReorderPoint: orm.NewField[int32]("reorder_point", "stock"),
	ReorderQuantity: orm.NewField[int32]("reorder_quantity", "stock"),
	BinLocation: orm.NewField[string]("bin_location", "stock"),
	IsActive: orm.NewField[bool]("is_active", "stock"),
	AllowBackorder: orm.NewField[bool]("allow_backorder", "stock"),
	CreatedAt: orm.NewField[time.Time]("created_at", "stock"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "stock"),
	LastCountedAt: orm.NewField[time.Time]("last_counted_at", "stock"),
}



// Validate validates the StockMovement model
func (m *StockMovement) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// StockMovementObjects provides type-safe operations for StockMovement
// Uses generic orm.Manager[StockMovement] and orm.BaseQuerySet[StockMovement]
var StockMovementObjects, _ = orm.NewManager[StockMovement]("stock_movements")

// StockMovementFields provides type-safe field access for StockMovement
type StockMovementFields struct {
	Id orm.FieldExpression[int64]
	StockId orm.FieldExpression[int64]
	ProductVariantId orm.FieldExpression[int64]
	WarehouseId orm.FieldExpression[int64]
	Type orm.FieldExpression[string]
	Quantity orm.FieldExpression[int32]
	QuantityBefore orm.FieldExpression[int32]
	QuantityAfter orm.FieldExpression[int32]
	ReferenceType orm.FieldExpression[string]
	ReferenceId orm.FieldExpression[int64]
	ReferenceNumber orm.FieldExpression[string]
	FromWarehouseId orm.FieldExpression[int64]
	ToWarehouseId orm.FieldExpression[int64]
	Reason orm.FieldExpression[string]
	Notes orm.FieldExpression[string]
	UserId orm.FieldExpression[int64]
	UserName orm.FieldExpression[string]
	UnitCost orm.FieldExpression[float64]
	TotalCost orm.FieldExpression[float64]
	CreatedAt orm.FieldExpression[time.Time]
	MovementDate orm.FieldExpression[time.Time]
}

var StockMovementFieldsInstance = StockMovementFields{
	Id: orm.NewField[int64]("id", "stock_movements"),
	StockId: orm.NewField[int64]("stock_id", "stock_movements"),
	ProductVariantId: orm.NewField[int64]("product_variant_id", "stock_movements"),
	WarehouseId: orm.NewField[int64]("warehouse_id", "stock_movements"),
	Type: orm.NewField[string]("type", "stock_movements"),
	Quantity: orm.NewField[int32]("quantity", "stock_movements"),
	QuantityBefore: orm.NewField[int32]("quantity_before", "stock_movements"),
	QuantityAfter: orm.NewField[int32]("quantity_after", "stock_movements"),
	ReferenceType: orm.NewField[string]("reference_type", "stock_movements"),
	ReferenceId: orm.NewField[int64]("reference_id", "stock_movements"),
	ReferenceNumber: orm.NewField[string]("reference_number", "stock_movements"),
	FromWarehouseId: orm.NewField[int64]("from_warehouse_id", "stock_movements"),
	ToWarehouseId: orm.NewField[int64]("to_warehouse_id", "stock_movements"),
	Reason: orm.NewField[string]("reason", "stock_movements"),
	Notes: orm.NewField[string]("notes", "stock_movements"),
	UserId: orm.NewField[int64]("user_id", "stock_movements"),
	UserName: orm.NewField[string]("user_name", "stock_movements"),
	UnitCost: orm.NewField[float64]("unit_cost", "stock_movements"),
	TotalCost: orm.NewField[float64]("total_cost", "stock_movements"),
	CreatedAt: orm.NewField[time.Time]("created_at", "stock_movements"),
	MovementDate: orm.NewField[time.Time]("movement_date", "stock_movements"),
}



// Validate validates the StockAlert model
func (m *StockAlert) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// StockAlertObjects provides type-safe operations for StockAlert
// Uses generic orm.Manager[StockAlert] and orm.BaseQuerySet[StockAlert]
var StockAlertObjects, _ = orm.NewManager[StockAlert]("stock_alerts")

// StockAlertFields provides type-safe field access for StockAlert
type StockAlertFields struct {
	Id orm.FieldExpression[int64]
	StockId orm.FieldExpression[int64]
	ProductVariantId orm.FieldExpression[int64]
	WarehouseId orm.FieldExpression[int64]
	AlertType orm.FieldExpression[string]
	CurrentQuantity orm.FieldExpression[int32]
	Threshold orm.FieldExpression[int32]
	Status orm.FieldExpression[string]
	ResolvedByUserId orm.FieldExpression[int64]
	ResolvedByUserName orm.FieldExpression[string]
	ResolutionNotes orm.FieldExpression[string]
	NotificationSent orm.FieldExpression[bool]
	NotificationSentAt orm.FieldExpression[time.Time]
	CreatedAt orm.FieldExpression[time.Time]
	UpdatedAt orm.FieldExpression[time.Time]
	AcknowledgedAt orm.FieldExpression[time.Time]
	ResolvedAt orm.FieldExpression[time.Time]
}

var StockAlertFieldsInstance = StockAlertFields{
	Id: orm.NewField[int64]("id", "stock_alerts"),
	StockId: orm.NewField[int64]("stock_id", "stock_alerts"),
	ProductVariantId: orm.NewField[int64]("product_variant_id", "stock_alerts"),
	WarehouseId: orm.NewField[int64]("warehouse_id", "stock_alerts"),
	AlertType: orm.NewField[string]("alert_type", "stock_alerts"),
	CurrentQuantity: orm.NewField[int32]("current_quantity", "stock_alerts"),
	Threshold: orm.NewField[int32]("threshold", "stock_alerts"),
	Status: orm.NewField[string]("status", "stock_alerts"),
	ResolvedByUserId: orm.NewField[int64]("resolved_by_user_id", "stock_alerts"),
	ResolvedByUserName: orm.NewField[string]("resolved_by_user_name", "stock_alerts"),
	ResolutionNotes: orm.NewField[string]("resolution_notes", "stock_alerts"),
	NotificationSent: orm.NewField[bool]("notification_sent", "stock_alerts"),
	NotificationSentAt: orm.NewField[time.Time]("notification_sent_at", "stock_alerts"),
	CreatedAt: orm.NewField[time.Time]("created_at", "stock_alerts"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "stock_alerts"),
	AcknowledgedAt: orm.NewField[time.Time]("acknowledged_at", "stock_alerts"),
	ResolvedAt: orm.NewField[time.Time]("resolved_at", "stock_alerts"),
}



// Validate validates the StockTransfer model
func (m *StockTransfer) Validate() error {
	validator := validation.NewValidator()
	return validation.ValidateModel(validator, m)
}

// StockTransferObjects provides type-safe operations for StockTransfer
// Uses generic orm.Manager[StockTransfer] and orm.BaseQuerySet[StockTransfer]
var StockTransferObjects, _ = orm.NewManager[StockTransfer]("stock_transfers")

// StockTransferFields provides type-safe field access for StockTransfer
type StockTransferFields struct {
	Id orm.FieldExpression[int64]
	TransferNumber orm.FieldExpression[string]
	FromWarehouseId orm.FieldExpression[int64]
	ToWarehouseId orm.FieldExpression[int64]
	ProductVariantId orm.FieldExpression[int64]
	Quantity orm.FieldExpression[int32]
	Status orm.FieldExpression[string]
	TrackingNumber orm.FieldExpression[string]
	Carrier orm.FieldExpression[string]
	Notes orm.FieldExpression[string]
	Reason orm.FieldExpression[string]
	RequestedByUserId orm.FieldExpression[int64]
	RequestedByUserName orm.FieldExpression[string]
	ApprovedByUserId orm.FieldExpression[int64]
	ApprovedByUserName orm.FieldExpression[string]
	CreatedAt orm.FieldExpression[time.Time]
	UpdatedAt orm.FieldExpression[time.Time]
	ShippedAt orm.FieldExpression[time.Time]
	CompletedAt orm.FieldExpression[time.Time]
	CancelledAt orm.FieldExpression[time.Time]
}

var StockTransferFieldsInstance = StockTransferFields{
	Id: orm.NewField[int64]("id", "stock_transfers"),
	TransferNumber: orm.NewField[string]("transfer_number", "stock_transfers"),
	FromWarehouseId: orm.NewField[int64]("from_warehouse_id", "stock_transfers"),
	ToWarehouseId: orm.NewField[int64]("to_warehouse_id", "stock_transfers"),
	ProductVariantId: orm.NewField[int64]("product_variant_id", "stock_transfers"),
	Quantity: orm.NewField[int32]("quantity", "stock_transfers"),
	Status: orm.NewField[string]("status", "stock_transfers"),
	TrackingNumber: orm.NewField[string]("tracking_number", "stock_transfers"),
	Carrier: orm.NewField[string]("carrier", "stock_transfers"),
	Notes: orm.NewField[string]("notes", "stock_transfers"),
	Reason: orm.NewField[string]("reason", "stock_transfers"),
	RequestedByUserId: orm.NewField[int64]("requested_by_user_id", "stock_transfers"),
	RequestedByUserName: orm.NewField[string]("requested_by_user_name", "stock_transfers"),
	ApprovedByUserId: orm.NewField[int64]("approved_by_user_id", "stock_transfers"),
	ApprovedByUserName: orm.NewField[string]("approved_by_user_name", "stock_transfers"),
	CreatedAt: orm.NewField[time.Time]("created_at", "stock_transfers"),
	UpdatedAt: orm.NewField[time.Time]("updated_at", "stock_transfers"),
	ShippedAt: orm.NewField[time.Time]("shipped_at", "stock_transfers"),
	CompletedAt: orm.NewField[time.Time]("completed_at", "stock_transfers"),
	CancelledAt: orm.NewField[time.Time]("cancelled_at", "stock_transfers"),
}


